config/routes.rb
Rails.application.routes.draw do
  root 'static#home'

  get '/about' => 'static#about'

  resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base

  validates :title, :author, :body, presence: true
  mount_uploader :image, ImageUploader

  def slug
    title.downcase.gsub(" ", "-")
  end

  def to_param
    "#{id}-#{slug}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all.order('created_at desc')
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      redirect_to posts_path
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :author, :body, :image)
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def title(page_title)
    content_for(:title) { page_title }
  end

  def markdown(text)
    options = {
      filter_html: true,
      hard_wrap: true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink: true,
      superscript: true,
      disable_indented_code_blocks: true,
      strikethrough: true,
      underline: true,
      highlight: true,
      quote: true,
      tables: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/_navbar.html.erb
<nav>
  <%= link_to 'Home', root_path %>
  <%= link_to 'About', about_path %>
  <%= link_to 'Blog', posts_path %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? content_for(:title) : "Artist Name" %></title>
  <%= stylesheet_link_tag    "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navbar' %>
  <%= yield %>

  <%= javascript_include_tag "application" %>
</body>
</html>

app/views/posts/_blog_post_form.html.erb
<!-- Error Report -->
<% if @post.errors.any? %>
  <div id="error_explanation">
    <h2>Please fix <%= pluralize(@post.errors.count, "error") %>:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<!-- Form -->
<div class="blog-form">
  <%= form_for @post do |f| %>
    <div>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>
    <div>
      <%= f.label :author %><br>
      <%= f.text_field :author %>
    </div>
    <div>
      <%= f.label :image %><br>
      <%= f.file_field :image %>
    </div>
    <div>
      <%= f.label :body %><br>
      <%= f.text_area :body, size: "60x25" %>
    </div>
    <%= f.submit %>
  <% end %>

  <p><%= link_to 'Cancel', posts_path %></p>
</div>

<!-- Markdown key-table -->
<div class="key-table">
  <table>
    <tr>
      <th>Effect</th>
      <th>Markdown</th>
    </tr>
    <tr>
      <td><strong>bold<strong></td>
        <td>**bold**</td>
      </tr>
      <tr>
        <td><em>italic<em></td>
          <td>*italic*</td>
        </tr>
        <tr>
          <td class="underline">underline</td>
          <td>_underline_</td>
        </tr>
        <tr>
          <td><span class="highlight">highlight</span></td>
          <td>==highlight==</td>
        </tr>
        <tr>
          <td><span class="strikethrough">strikethrough</span></td>
          <td>~~strikethrough~~</td>
        </tr>
        <tr>
          <td><h1>h1 Headline</h1></td>
          <td>#h1 Headline#</td>
        </tr>
        <tr>
          <td><h2>h2 Headline</h2></td>
          <td>##h2 Headline##</td>
        </tr>
        <tr>
          <td><h3>h3 Headline</h3></td>
          <td>###h3 Headline###</td>
        </tr>
        <tr>
          <td><h4>h4 Headline</h4></td>
          <td>####h4 Headline####</td>
        </tr>
        <!-- <tr>
        <td><h5>h5 Headline</h5></td>
        <td>#####h5 Headline#####</td>
      </tr>
      <tr>
      <td><h6>h6 Headline</h6></td>
      <td>######h6 Headline######</td>
    </tr> -->
    <tr>
      <td>___________ (line break)</td>
      <td>*** or ___ (3 underscores)</td>
    </tr>
    <tr>
      <td><a href="">Click Me!</a></td>
      <td>[Click Me!] (http://google.com)</td>
    </tr>
    <tr>
      <td>52<sup>nd</sup></td>
      <td>52^(nd)</td>
    </tr>
    <tr>
      <td>This is an Ordered List:
        <ol>
          <li>
            First item
            <ul>
              <li>first sub-item</li>
            </ul>
          </li>
          <li>Second item</li>
        </ol>
      </td>
      <td>This is an Ordered List:<br><br>1. First item<br>&nbsp;&nbsp;1. first sub-item (lead with 2 empty spaces)<br>2. Second item</td>
    </tr>
    <tr>
      <td>This is an Unordered List:
        <ul>
          <li>
            First item
            <ul>
              <li>sub-item</li>
            </ul>
          </li>
          <li>Second item</li>
        </ul>
      </td>
      <td>This is an Unordered List:<br><br>* First item<br>&nbsp;&nbsp;* sub-item (lead with 2 empty spaces)<br>* Second item</td>
    </tr>
    <tr>
      <td>
        A quote from Vincent van Gogh:
        <blockquote>I am seeking. I am striving. I am in it with all my heart.</blockquote>
      </td>
      <td>A quote from Vincent van Gogh:<br><br>> I am seeking. I am striving. I am in it with all my heart.</td>
    </tr>
    <tr>
      <td>
        <table>
          <tr>
            <th>column 1</th>
            <th>column 2</th>
          </tr>
          <tr>
            <td>cell</td>
            <td class="right-cell">cell</td>
          </tr>
          <tr>
            <td>cell</td>
            <td class="right-cell">cell</td>
          </tr>
        </table>
      </td>
      <td>
        column 1 | column 2<br>
        --- | ---:<br>
        cell | cell<br>
        cell | cell<br><br>
        (align cell text right) ---:<br>
        (align cell text center) :---:

      </td>
    </tr>
  </table>
</div>

app/views/posts/edit.html.erb
<%- title "Edit \"#{@post.title}\" | Blog | Artist Name" %>

<h1>Edit Post</h1>

<%= render 'blog_post_form' %>

app/views/posts/index.html.erb
<%- title "Blog | Artist Name" %>

<h1>Blog</h1>
<p><%= link_to 'New Post', new_post_path %></p>
<hr />

<% @posts.each do |post| %>
  <h2><%= post.title %></h2>
  <!-- <h3><%= post.author %></h3> -->
  <h3><i class="fa fa-clock-o"></i>&nbsp;<%= post.created_at.strftime("%b %d, %Y / %I:%M%P") %></h3>
  <!-- <h3><i class="fa fa-calendar"></i>&nbsp;<%= post.created_at.strftime("%b %d, %Y") %></h3> -->
  <%= image_tag(post.image.thumb) if post.image? %>
  <p><%= markdown(truncate(post.body, length: 140, separator: ' ')) %></p>
  <h5>Published <%= time_ago_in_words post.created_at %> ago</h5>

  <%= link_to 'Show', post_path(post) %>
  <%= link_to 'Edit', edit_post_path(post) %>
  <%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %>

  <% if post != @posts.last %>
    <hr />
  <% end %>
<% end %>

app/views/posts/new.html.erb
<%- title "New Post | Blog | Artist Name" %>

<h1>New Post</h1>

<%= render 'blog_post_form' %>

app/views/posts/show.html.erb
<%- title "#{@post.title} | Blog | Artist Name" %>

<div>
  <h1><%= @post.title %></h1>
  <!-- <h2><%= @post.author %></h2> -->
  <h3><i class="fa fa-clock-o"></i>&nbsp;<%= @post.created_at.strftime("%b %d, %Y / %I:%M%P") %></h3>

  <div>
    <%=image_tag(@post.image) if @post.image? %>
  </div>

  <p><%= markdown(@post.body) %></p>

  <!-- Twitter share button -->
  <a href="https://twitter.com/share" class="twitter-share-button" data-text="<%= @post.title %>" data-via="Lando726">Tweet</a>
  <script>
  !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');
  </script>

  <!-- Facebook share button -->
  <div id="fb-root"></div>
  <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.0";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>
  <!-- ***Need to set dynamic url below still*** -->
  <div class="fb-share-button" data-href="http://developers.facebook.com" data-layout="button_count"></div>

  <!-- Disqus comments -->
  <div id="disqus_thread"></div>
  <script type="text/javascript">
  /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
  var disqus_shortname = 'artisttestblog'; // required: replace example with your forum shortname

  /* * * DON'T EDIT BELOW THIS LINE * * */
  (function() {
    var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
    dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>


  <%= link_to 'Back', posts_path %>
</div>